configfile: "config.yaml"

import pandas as pd

# Load medication table to get number of rows
med_df = pd.read_csv(config["medication_params_file"])

MED_INDICES = range(len(med_df))
PARAM_INDICES = range(config["n_param_sets"])

rule all:
    input:
        expand(
            "results/{sub}/med_{med}_param_{param}.npz",
            sub=config["subjects"],
            med=MED_INDICES,
            param=PARAM_INDICES
        )

rule run_simulation:
    output:
        "results/{sub}/med_{med}_param_{param}.npz"
    shell:
        """
        python run_medication_sim.py \
            {wildcards.sub} \
            {wildcards.med} \
            {wildcards.param} \
            {output}
        """